services:
  db:
    image: postgres:18-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ledger
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
